query Favorites {
	getFavorites  @cache(policy: NetworkOnly) {
		id
		title
		description
		price
		createdAt
		location
		oldPrice
		isFavorited

		user {
			id
			rating
			name
			surname
		}
	}
}
