query HeaderMe {
	me {
		id
		name
		surname
		companyName
		email
		emailVerified

		adverts {
			id
			title
			price
			description
			location
			createdAt
			photoUrl
			additionalPhotos
			oldPrice
		}
	}
}
