version: "3"

services:
  # db:
  #   image: postgres:latest
  #   user: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: ss.lv
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - RUST_BACKTRACE=1
#     depends_on:
#       - db

# volumes:
#   db_data:
