
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "80:80"
    env_file:
      - ./backend/.env
    environment:
      - RUST_BACKTRACE=1
  # telegram:
  #   build: ./telegram-bot
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend
