services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /backend/  
    ports:
      - "4173:4173"  
    environment:
      VITE_API_URL: /backend/ 
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:80"  
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
      REDIS_URL: redis://redis:6379
      OTHER_ENV_VAR: value
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    # ports:
    #   - "5432:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    # ports:
    #   - "6379:6379"  
    volumes:
      - redis_data:/data
    networks:
      - app-network
  
  tgbot:
    build: ./telegram-bot
    env_file:
      - ./telegram-bot/docker.env
    networks:
      - app-network
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge
