services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /backend/  
    ports:
      - "4173:4173"  
    environment:
      VITE_API_URL: /backend/ 
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build: ./backend
    ports:
      - "8080:80"  
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    # ports:
    #   - "5432:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    # ports:
    #   - "6379:6379"  
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
  
  tgbot:
    build: ./telegram-bot
    env_file:
      - ./telegram-bot/docker.env
    networks:
      - app-network
    depends_on:
      - db
      - redis
    restart: always

volumes:
  db_data:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
