query User($id: Int!) {
	user(id: $id) {
		id
		name
		surname
		phone
		email
		rating
		adverts {
			id
			title
			price
			description
			location
			createdAt
			available
			photoUrl
			additionalPhotos
			oldPrice
			isFavorited

			review {
				rating
				id
			}
		}
	}
}
