query User($id: Int!) {
  user(id: $id) {
    id
    name
    surname
    phone
    email
    rating
    avatarUrl
    telegramUsername
    adverts {
      id
      title
      price
      description
      lat
      lon
      createdAt
      available
      photoUrl
      additionalPhotos
      oldPrice
      isFavorited

      review {
        rating
        id
        message
      }
    }

    reviewedAdverts {
      title
      lat
      lon
      price
      createdAt
      review {
        message
        rating
        createdAt
      }
    }

    advertsWithReviews {
      title
      price
      lat
      lon
      available
      review {
        rating
        message
        createdAt
        user {
          name
        }
      }
    }
  }
}
