query Search($title: String!, $location: String, $category: String, $offset: Int!) {
  searchAdverts(title: $title, location: $location, category: $category, offset:$offset) {
    id
    title
    price
    description
    location
    createdAt
    available
    photoUrl
    additionalPhotos
    oldPrice
    isFavorited
    user {
      id
      name
      surname
      phone
      email
      rating
      avatarUrl
      telegramUsername
    }
    review {
      rating
      id
      message
    }
  }
}
