query me {
  me {
    id
    name
    surname
    companyName
    email
    emailVerified
    rating
    telegramUsername
    phone
    role

    reviewedAdverts {
      title
      lat
      lon
      price
      createdAt
      photoUrl
      review {
        message
        rating
        createdAt
      }
    }

    advertsWithReviews {
      title
      price
      lat
      lon
      available
      photoUrl
      review {
        rating
        message
        createdAt
        user {
          name
        }
      }
    }

    adverts {
      id
      title
      price
      description
      lat
      lon
      createdAt
      photoUrl
      additionalPhotos
      oldPrice
      available

      review {
        rating
        id
        message
      }
    }
  }
}
