query HeaderMe {
  me {
    id
    name
    email
    emailVerified

    adverts {
      id
      title
      price
      description
      location
      createdAt
      photoUrl
      additionalPhotos
      oldPrice
    }
  }
}
