[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "0.12" }
async-graphql = {version="6.0.6", features=["chrono"]}
chrono = "0.4.31"