query Advert($id: Int!) {
  advert(id: $id) {
    id
    title
    description
    price
    createdAt
    lat
    lon
    oldPrice
    isFavorited
    photoUrl
    additionalPhotos
    soldTo
    available


    review {
      id
      rating
      message
      createdAt
    }

    specs {
      id
      key
      value
    }

    user {
      id
      rating
      name
      surname
      createdAt
    }
  }
}
