query Advert($id: Int!) {
  advert(id: $id) {
    id
    title
    description
    price
    createdAt
    location
    oldPrice
    isFavorited
    photoUrl
    additionalPhotos

	specs {
		id
		key
		value
	}

    user {
      id
      rating
      name
      surname
      createdAt
    }
  }
}
